@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6IlRlc3RhenpvLjk5IiwiaXNzIjoiYXV0aC1zZXJ2aWNlLXVuaWppcmEiLCJleHAiOjE2NDMzMDczMjksInR5cGUiOiJBVVRIT1JJWkFUSU9OIiwiaWF0IjoxNjQzMzAzNzI5LCJ1c2VybmFtZSI6InBhb2xhZ3VhcmFzY2lAZ21haWwuY29tIn0.vVzOpOdn5kP3K8jUGXMJllYmD7yqsAVOfpg5M3KEx10

# @token = {{login.response.body.token}}

@projectid = 38
@backlogid = 41
@sprintid = 50
@roadmapid = 95
############## AUTH #############


### 
POST http://localhost:7080/auth/register
Content-Type: application/json

{
  "username": "paolaguarasci@gmail.com",
  "password": "Testazzo.99"
}

###

# @name login
POST http://localhost:7080/auth/authenticate
Content-Type: application/json
Accept: application/json

{
  "username": "paolaguarasci@gmail.com",
  "password": "Testazzo.99"
}

###
GET http://localhost:7080/auth/me
Authorization: Bearer {{token}}

##### Project #####################################

###
GET http://localhost:7080/projects
Authorization: Bearer {{token}}

###
GET http://localhost:7080/projects/{{projectid}}/sprint
Authorization: Bearer {{token}}

###
POST http://localhost:7080/projects
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Test-1",
    "key": "TS1"
}



##### Backlog #####################################

###
GET http://localhost:7080/projects/{{projectid}}/backlogs
Authorization: Bearer {{token}}

###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}
Authorization: Bearer {{token}}
###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/insertions
Authorization: Bearer {{token}}

###

PUT http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/insertions/68
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": 68,
    "item": {
      "createdAt": "2022-01-07T21:23:59.725031",
      "updatedAt": "2022-01-07T21:23:59.725038",
      "id": 4,
      "summary": "Summary 2",
      "description": "Item 2",
      "measureUnit": "Unit",
      "evaluation": 12,
      "tags": "#tag1#,#tag2#",
      "type": "task",
      "status": "OPEN",
      "owner": {
        "id": 1,
        "username": "paolaguarasci@gmail.com",
        "activated": false,
        "disabled": false,
        "avatar": "https://eu.ui-avatars.com/api/?background=0D8ABC&color=fff&name=P+G",
        "createdAt": "2022-01-07T21:23:59.581926",
        "updatedAt": "2022-01-07T21:23:59.58194"
      },
      "fatherId": null,
      "sons": [],
      "notes": [],
      "assignees": [
        {
          "id": 80,
          "itemId": 4,
          "assignee": {
            "id": 1,
            "username": "paolaguarasci@gmail.com",
            "activated": false,
            "disabled": false,
            "avatar": "https://eu.ui-avatars.com/api/?background=0D8ABC&color=fff&name=P+G",
            "createdAt": "2022-01-07T21:23:59.581926",
            "updatedAt": "2022-01-07T21:23:59.58194"
          }
        }
      ]
    },
    "priority": 3
}




###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}

###
POST http://localhost:7080/projects/{{projectid}}/backlogs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "project": {
    "id": 2,
    "name": "Test-1",
    "key": "TS1",
    "icon": null,
    "ownerId": 1
  }
}


###
DELETE http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/
Authorization: Bearer {{token}}


#### Item (Backlog) #####################################

###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}

###
POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "item": {
  
  "createdAt": "2021-12-28T09:27:11.912868579",
  "updatedAt": "2021-12-28T09:27:11.912872259",
  "id": 13,
  "summary": "HELLO I'M AN Ticket 2",
  "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
  "measureUnit": "story points",
  "evaluation": 1,
  "tags": "#BACKEND#;#FRONTEND#",
  "type": "task",
  "status": null,
  "owner": {
    "id": 1,
    "username": "paolaguarasci@gmail.com",
    "activated": false,
    "disabled": false,
    "createdAt": "2021-12-28T09:27:11.912982507",
    "updatedAt": "2021-12-28T09:27:11.912983189"
  },
  "father": null,
  "notes": [],
  "assignees": []
  
  },
  "priority": "1"
}

###
PUT http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items/6
Authorization: Bearer {{token}}
Content-Type: application/json

{

    "id": 6,
    "item": {
      "createdAt": "2021-12-28T09:24:33.638628",
      "updatedAt": "2021-12-28T09:24:33.638639",
      "id": 5,
      "summary": "HELLO I'M AN EPIC 0",
      "description": "HI I'M AN EPIC AND I WANTO TO BE A GOOD EPIC",
      "measureUnit": "story points",
      "evaluation": 15,
      "tags": "#BACKEND#;#FRONTEND#",
      "type": "epic",
      "status": null,
      "owner": {
        "id": 1,
        "username": "paolaguarasci@gmail.com",
        "activated": false,
        "disabled": false,
        "createdAt": "2021-12-28T09:19:12.40948",
        "updatedAt": "2021-12-28T09:19:12.409526"
      },
      "father": null,
      "notes": [],
      "assignees": []
    },
   "priority": "2"
}





#### Sprint #####################################

###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/sprints
Authorization: Bearer {{token}}

###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/sprints/{{sprintid}}/
Authorization: Bearer {{token}}

###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/sprints/{{sprintid}}/insertions
Authorization: Bearer {{token}}




###
PUT http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/sprints/{{sprintid}}/insertions/92
Authorization: Bearer {{token}}

###
POST  http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/sprints
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sprint",
  "startingDate": "2022-01-01",
  "endingDate": "2022-01-30"
}

### Start spirnt (cioe' set con le date)
PUT  http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/sprints/{{sprintid}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sprint",
  "startingDate": "2022-01-01",
  "endingDate": "2022-01-31"
}

###
PUT  http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/sprints/{{sprintid}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "startingDate": "2022-01-01",
  "endingDate": "2022-01-31",
  "insertions": [],
  "backlogId": 3
}

#### Item (Sprint) #####################################


###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/sprints/{{sprintid}}/items
Authorization: Bearer {{token}}

###
POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/sprints/{{sprintid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": 26,
    "item": {
      "createdAt": "2021-12-27T11:28:16.006408",
      "updatedAt": "2021-12-27T11:28:16.006412",
      "id": 22,
      "summary": "HELLO I'M AN Ticket 6",
      "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
      "measureUnit": "story points",
      "evaluation": 1,
      "tags": "#BACKEND#;#FRONTEND#",
      "type": "task",
      "status": null,
      "owner": {
        "id": 1,
        "username": "paolaguarasci@gmail.com",
        "activated": false,
        "disabled": false,
        "createdAt": "2021-12-27T10:41:09.714479",
        "updatedAt": "2021-12-27T10:41:09.714497"
      },
      "father": null,
      "notes": [],
      "assignees": []
    },
    "backlog": {
      "id": 3,
      "project": {
        "id": 2,
        "name": "Test-1",
        "key": "TS1",
        "icon": null,
        "ownerId": 1,
        "createdAt": "2021-12-27T11:12:37.152143",
        "updatedAt": "2021-12-27T11:12:37.152144"
      },
      "sprints": [
        {
          "id": 6,
          "startingDate": null,
          "endingDate": "2022-01-15",
          "insertions": [],
          "backlogId": 3
        }
      ],
      "insertions": null
    },
    "priority": 1
}


### Item (generici) #####################################

### Tutti gli item 
GET http://localhost:7080/items/2
Authorization: Bearer {{token}}

### 

### Tutti gli item assegnati all'utente
GET http://localhost:7080/items/by-user/1
Authorization: Bearer {{token}}

### 

POST http://localhost:7080/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "HELLO I'M AN EPIC 0",
    "description": "HI I'M AN EPIC AND I WANTO TO BE A GOOD EPIC",
    "measureUnit": "story points",
    "evaluation": "10",
    "tags" : "#BACKEND#;#FRONTEND#",
    "type" : "epic",
    "owner" : { 
      "id": 1, 
      "username" : "paolaguarasci@gmail.com"
    }
}





###
POST http://localhost:7080/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "HELLO I'M AN EPIC 1",
    "description": "HI I'M AN EPIC AND I WANTO TO BE A GOOD EPIC",
    "measureUnit": "story points",
    "evaluation": "100000",
    "tags" : "#BACKEND#;#FRONTEND#",
    "type" : "epic",
    "owner" : { 
      "id": 1, 
      "username" : "paolaguarasci@gmail.com"
    }
}

###

PUT http://localhost:7080/items/13
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "createdAt": "2022-01-08T18:09:35.141734",
  "updatedAt": "2022-01-08T18:09:35.141743",
  "id": 13,
  "summary": "Summary 3aa",
  "description": "Item 3",
  "measureUnit": "Unit",
  "evaluation": 33,
  "tags": "#tag1#,#tag2#",
  "type": "task",
  "status": "DONE",
  "owner": {
    "id": 1,
    "username": "paolaguarasci@gmail.com",
    "activated": false,
    "disabled": false,
    "avatar": "https://eu.ui-avatars.com/api/?background=0D8ABC&color=fff&name=P+G",
    "createdAt": "2022-01-08T18:09:34.95546",
    "updatedAt": "2022-01-08T18:09:34.955475"
  },
  "fatherId": null,
  "sons": [],
  "notes": [],
  "assignees": [
    {
      "id": 105,
      "itemId": 13,
      "assigneeId": 1
    }
  ]
}


###


POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "item": {
    "id": 1,
    "summary": "HELLO I'M AN EPIC 1",
    "description": "HI I'M AN EPIC AND I WANTO TO BE A GOOD EPIC",
    "measureUnit": "story points",
    "evaluation": 100000,
    "tags": "#BACKEND#;#FRONTEND#",
    "type": "epic",
    "notes": [],
    "owner": {
      "id": 1,
      "username": "paolaguarasci@gmail.com",
      "activated": false,
      "disabled": false
    },
    "assignees": [],
    "father": null
  },
  "priority": "1"
}


###
POST http://localhost:7080/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "HELLO I'M AN EPIC 2",
    "description": "HI I'M AN EPIC AND I WANTO TO BE A GOOD EPIC",
    "measureUnit": "story points",
    "evaluation": "100000",
    "tags" : "#BACKEND#;#FRONTEND#",
    "type" : "epic",
    "owner" : { 
      "id": 1, 
      "username" : "paolaguarasci@gmail.com"
    }
}

###


POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "item": {
    "id": 2,
    "summary": "HELLO I'M AN EPIC 2",
    "description": "HI I'M AN EPIC AND I WANTO TO BE A GOOD EPIC",
    "measureUnit": "story points",
    "evaluation": 100000,
    "tags": "#BACKEND#;#FRONTEND#",
    "type": "epic",
    "notes": [],
    "owner": {
      "id": 1,
      "username": "paolaguarasci@gmail.com",
      "activated": false,
      "disabled": false
    },
    "assignees": [],
    "father": null
  },
  "priority": "1"
}


###
POST http://localhost:7080/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "HELLO I'M AN Ticket 1",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": "1",
    "tags" : "#BACKEND#;#FRONTEND#",
    "type" : "task",
    "owner" : { 
      "id": 1, 
      "username" : "paolaguarasci@gmail.com"
    }
}

###

POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "item": {
    "id": 3,
    "summary": "HELLO I'M AN Ticket 1",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": 1,
    "tags": "#BACKEND#;#FRONTEND#",
    "type": "task",
    "notes": [],
    "owner": {
      "id": 1,
      "username": "paolaguarasci@gmail.com",
      "activated": false,
      "disabled": false
    },
    "assignees": [],
    "father": 2
  },
  "priority": "1"
}

###
POST http://localhost:7080/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "HELLO I'M AN Ticket 2",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": "1",
    "tags" : "#BACKEND#;#FRONTEND#",
    "type" : "task",
    "owner" : { 
      "id": 1, 
      "username" : "paolaguarasci@gmail.com"
    }
}

###

POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "item": {
    "id": 4,
    "summary": "HELLO I'M AN Ticket 2",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": 1,
    "tags": "#BACKEND#;#FRONTEND#",
    "type": "task",
    "notes": [],
    "owner": {
      "id": 1,
      "username": "paolaguarasci@gmail.com",
      "activated": false,
      "disabled": false
    },
    "assignees": [],
    "father": null
  },
  "priority": "1"
}

###
POST http://localhost:7080/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "HELLO I'M AN Ticket 3",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": "1",
    "tags" : "#BACKEND#;#FRONTEND#",
    "type" : "task",
    "owner" : { 
      "id": 1, 
      "username" : "paolaguarasci@gmail.com"
    }
}

###

POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "item": {
    "id": 5,
    "summary": "HELLO I'M AN Ticket 3",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": 1,
    "tags": "#BACKEND#;#FRONTEND#",
    "type": "task",
    "notes": [],
    "owner": {
      "id": 1,
      "username": "paolaguarasci@gmail.com",
      "activated": false,
      "disabled": false
    },
    "assignees": [],
    "father": null
  },
  "priority": "1"
}

###
POST http://localhost:7080/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "HELLO I'M AN Ticket 4",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": "1",
    "tags" : "#BACKEND#;#FRONTEND#",
    "type" : "task",
    "owner" : { 
      "id": 1, 
      "username" : "paolaguarasci@gmail.com"
    }
}

###

POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "item": {
    "id": 6,
    "summary": "HELLO I'M AN Ticket 4",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": 1,
    "tags": "#BACKEND#;#FRONTEND#",
    "type": "task",
    "notes": [],
    "owner": {
      "id": 1,
      "username": "paolaguarasci@gmail.com",
      "activated": false,
      "disabled": false
    },
    "assignees": [],
    "father": null
  },
  "priority": "1"
}

###
POST http://localhost:7080/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "HELLO I'M AN Ticket 5",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": "1",
    "tags" : "#BACKEND#;#FRONTEND#",
    "type" : "task",
    "owner" : { 
      "id": 1, 
      "username" : "paolaguarasci@gmail.com"
    }
}

###

POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "item": {
    "id": 7,
    "summary": "HELLO I'M AN Ticket 5",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": 1,
    "tags": "#BACKEND#;#FRONTEND#",
    "type": "task",
    "notes": [],
    "owner": {
      "id": 1,
      "username": "paolaguarasci@gmail.com",
      "activated": false,
      "disabled": false
    },
    "assignees": [],
    "father": null
  },
  "priority": "1"
}

###
POST http://localhost:7080/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "HELLO I'M AN Ticket 6",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": "1",
    "tags" : "#BACKEND#;#FRONTEND#",
    "type" : "task",
    "owner" : { 
      "id": 1, 
      "username" : "paolaguarasci@gmail.com"
    }
}

###

POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "item": {
    "id": 8,
    "summary": "HELLO I'M AN Ticket 6",
    "description": "Ciao! I'M AN Ticket AND I WANTO TO BE A GOOD Ticket",
    "measureUnit": "story points",
    "evaluation": 1,
    "tags": "#BACKEND#;#FRONTEND#",
    "type": "task",
    "notes": [],
    "owner": {
      "id": 1,
      "username": "paolaguarasci@gmail.com",
      "activated": false,
      "disabled": false
    },
    "assignees": [],
    "father": null
  },
  "priority": "1"
}

###
POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/roadmaps
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 10,
  "backlogId": 41,
  "insertions": []
}

###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/roadmaps
Authorization: Bearer {{token}}

###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/roadmaps/{{roadmapid}}/insertions
Authorization: Bearer {{token}}

###
GET http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/roadmaps/{{roadmapid}}/tree
Authorization: Bearer {{token}}

###
POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/roadmaps/{{roadmapid}}/insertions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "startingDate": "2018-01-01",
  "endingDate": "2018-01-01",
  "item": {
    "id": 2,
    "summary": "Summary Epic 0",
    "description": "Epic 0",
    "measureUnit": "STORY_POINTS",
    "evaluation": 10,
    "tags": "#tag1#,#tag2#",
    "type": "EPIC",
    "status": "OPEN",
    "owner": {
      "id": 1,
      "username": "paolaguarasci@gmail.com",
      "status": "ACTIVE",
      "disabled": false,
      "avatar": null,
      "birthDate": null,
      "firstName": "",
      "lastName": "",
      "role": "",
      "description": "",
      "github": "",
      "linkedin": "",
      "phoneNumber": ""
    },
    "releaseId": null,
    "releaseVersion": null,
    "fatherId": null,
    "projectId": null,
    "sons": [],
    "notes": [],
    "assignees": [
      {
        "id": 3,
        "itemId": 2,
        "assigneeId": 1,
        "assigneeUsername": "paolaguarasci@gmail.com",
        "assigneeAvatar": null
      }
    ]
  },
  "roadmapId": "97"
}

###
POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/roadmaps/{{roadmapid}}/insertions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "startingDate": "2018-01-01",
  "endingDate": "2018-01-01",
  "item": 
  {
      "createdAt": "2022-01-27T15:00:23.061587",
      "updatedAt": "2022-01-27T15:00:23.061593",
      "id": 8,
      "summary": "Summary Story 0",
      "description": "Story 0",
      "measureUnit": "STORY_POINTS",
      "evaluation": 10,
      "tags": "#tag1#,#tag2#",
      "type": "STORY",
      "status": "OPEN",
      "owner": {
        "id": 1,
        "username": "paolaguarasci@gmail.com",
        "status": "REQUIRE_CONFIRM",
        "disabled": false,
        "avatar": null,
        "createdAt": "2022-01-27T15:00:22.872561",
        "updatedAt": "2022-01-27T15:00:22.872575",
        "birthDate": null,
        "firstName": "",
        "lastName": "",
        "role": "",
        "description": "",
        "github": "",
        "linkedin": "",
        "phoneNumber": ""
      },
      "releaseId": null,
      "releaseVersion": null,
      "fatherId": 2,
      "projectId": null,
      "sons": [],
      "notes": [],
      "assignees": [
        {
          "id": 9,
          "itemId": 8,
          "assigneeId": 1,
          "assigneeUsername": "paolaguarasci@gmail.com",
          "assigneeAvatar": null
        }
      ]
    },
  "roadmapId": "97"
}


###
POST http://localhost:7080/projects/{{projectid}}/backlogs/{{backlogid}}/roadmaps/{{roadmapid}}/insertions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "startingDate": "2018-01-01",
  "endingDate": "2018-01-01",
  "item": 
  {
      "createdAt": "2022-01-27T15:00:23.131479",
      "updatedAt": "2022-01-27T15:00:23.13148",
      "id": 14,
      "summary": "Summary Story 3",
      "description": "Story 3",
      "measureUnit": "STORY_POINTS",
      "evaluation": 13,
      "tags": "#tag1#,#tag2#",
      "type": "STORY",
      "status": "OPEN",
      "owner": {
        "id": 1,
        "username": "paolaguarasci@gmail.com",
        "status": "REQUIRE_CONFIRM",
        "disabled": false,
        "avatar": null,
        "createdAt": "2022-01-27T15:00:22.872561",
        "updatedAt": "2022-01-27T15:00:22.872575",
        "birthDate": null,
        "firstName": "",
        "lastName": "",
        "role": "",
        "description": "",
        "github": "",
        "linkedin": "",
        "phoneNumber": ""
      },
      "releaseId": null,
      "releaseVersion": null,
      "fatherId": 2,
      "projectId": null,
      "sons": [],
      "notes": [],
      "assignees": [
        {
          "id": 15,
          "itemId": 14,
          "assigneeId": 1,
          "assigneeUsername": "paolaguarasci@gmail.com",
          "assigneeAvatar": null
        }
      ]
    },
  "roadmapId": "97"
}

###